add district-tasks
district0x/deployments pull request #1
Opened 2018-11-29 15:14 UTC by kwladyka

WIP Waiting for DNS settings

2018-11-29 16:11 UTC, fbielejec requested changes

2018-11-29 16:11 UTC, fbielejec commented on district-tasks/ui/district-tasks.io
> +  listen 80 default_server;
80, 6300, 5001, 8080, 8545 will be occupied, use different port

2018-11-29 16:11 UTC, fbielejec commented on district-tasks/ui/X0X.html
> +<!doctype html>
reuse existing when building e.g. https://github.com/district0x/x0x

2018-11-29 16:11 UTC, fbielejec commented on district-tasks/docker-compose.yml
> +    - 80:80
occupied port

2018-12-03 14:33 UTC, kwladyka commented
Added changes

2018-12-11 14:03 UTC, fbielejec requested changes

2018-12-11 14:03 UTC, fbielejec commented on district-tasks/docker-compose.yml
> +    - qa-net
this network is never created, is it needed?

2018-12-11 14:03 UTC, fbielejec commented on district-tasks/docker-compose.yml
> +    - server/config.edn:/app/config.edn
why mount a volume just for this config? Just keep the config in container.

2018-12-11 14:03 UTC, fbielejec commented on district-tasks/docker-compose.yml
> +    - ui/nginx.conf:/etc/nginx/nginx.conf
no need to mount these volumes, we run separate nginx processes, configs can stay in containers

2018-12-11 14:03 UTC, fbielejec commented on district-tasks/server/smart_contracts.cljs
> +
are these addresses part of the repo you build in the containers? If not add the file before building

2018-12-11 14:03 UTC, fbielejec commented on district-tasks/ui/district-tasks.io
> +server {
use ipfs as proxy, that's how it will run in production.

2019-08-07 10:05 UTC, closed without merging